// 실제 앱 캡처를 재생하는 안내입니다. 앱에 변경 요청을 보내지 않습니다.
window.MANUAL_DATA = {
  title: "재활 케어 사용 안내",
  version: "1.0.0",
  updatedAt: "2026-09-27",
  centerName: "재활센터 시연센터",
  scenarios: [
    {
      id: "center-setup",
      title: "새 센터의 운영 준비하기",
      summary:
        "센터를 만들고 이용기간과 관리자를 정한 뒤 관리자 화면까지 확인해요.",
      roles: ["SUPER_ADMIN", "ADMIN"],
      category: "센터 운영",
      minutes: 3,
      featured: false,
      prerequisites: [
        "슈퍼 관리자가 센터를 만들고 관리자를 지정해요.",
        "관리자를 맡을 사람은 회원가입을 마친 계정이어야 해요.",
      ],
      outcome:
        "재활센터 새봄센터의 이용기간과 관리자 지정이 완료되어 오지훈이 센터 관리를 시작할 수 있어요.",
      promoStepIds: [
        "setup-02",
        "setup-04",
        "setup-07",
        "setup-07-confirm",
        "setup-08",
        "setup-09",
      ],
      steps: [
        {
          id: "setup-01",
          title: "새 센터를 만들어요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "센터 관리에서 센터 만들기를 눌러요.",
          result: "새 센터의 이름을 입력할 수 있어요.",
          duration: 6500,
          transition: "",
          centerName: "전체 센터",
          image: "assets/setup-01.jpg",
          alt: "운영관리자(manualsuper) · 새 센터를 만들어요. 센터 관리에서 센터 만들기를 눌러요.",
          hotspot: {
            x: 0.027906976744186046,
            y: 0.37975694444444447,
            w: 0.9093023255813953,
            h: 0.05555555555555555,
            label: "센터 만들기",
          },
        },
        {
          id: "setup-02",
          title: "센터 이름을 입력해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "재활센터 새봄센터라고 입력하고 센터 만들기를 눌러요.",
          result: "등록할 센터의 이름을 다시 확인해요.",
          duration: 6500,
          transition: "",
          centerName: "새 센터 준비",
          image: "assets/setup-02.jpg",
          alt: "운영관리자(manualsuper) · 센터 이름을 입력해요. 재활센터 새봄센터라고 입력하고 센터 만들기를 눌러요.",
          hotspot: {
            x: 0.4965116279069767,
            y: 0.5346354166666667,
            w: 0.4011627906976744,
            h: 0.05555555555555555,
            label: "이름 입력 후 센터 만들기",
          },
        },
        {
          id: "setup-02-confirm",
          title: "센터 생성을 확인해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "센터 이름이 맞는지 보고 확인을 눌러요.",
          result: "새 센터가 센터 관리 목록에 추가돼요.",
          duration: 6500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-02-confirm.jpg",
          alt: "운영관리자(manualsuper) · 센터 생성을 확인해요. 센터 이름이 맞는지 보고 확인을 눌러요.",
          hotspot: {
            x: 0.4941860465116279,
            y: 0.5675520833333333,
            w: 0.3930232558139535,
            h: 0.05555555555555555,
            label: "센터 이름 확인",
          },
        },
        {
          id: "setup-03",
          title: "센터 이용기간을 정해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "새봄으로 검색한 센터 카드에서 이용기간 설정을 눌러요.",
          result: "센터가 사용할 기간을 설정할 수 있어요.",
          duration: 6500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-03.jpg",
          alt: "운영관리자(manualsuper) · 센터 이용기간을 정해요. 새봄으로 검색한 센터 카드에서 이용기간 설정을 눌러요.",
          hotspot: {
            x: 0.06744186046511629,
            y: 0.8136111111111111,
            w: 0.4011627906976744,
            h: 0.05555555555555555,
            label: "이용기간 설정",
          },
        },
        {
          id: "setup-04",
          title: "3개월을 선택하고 저장해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption:
            "3개월을 선택했어요. 9월 27일부터 12월 26일까지인지 확인하고 이용기간 저장을 눌러요.",
          result: "시작일과 종료일은 날짜를 눌러 달력에서 고를 수도 있어요.",
          duration: 8500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-04.jpg",
          alt: "운영관리자(manualsuper) · 3개월을 선택하고 저장해요. 3개월을 선택했어요. 9월 27일부터 12월 26일까지인지 확인하고 이용기간 저장을 눌러요.",
          hotspot: {
            x: 0.07674418604651163,
            y: 0.73546875,
            w: 0.8465116279069768,
            h: 0.05555555555555555,
            label: "3개월 이용기간 저장",
          },
        },
        {
          id: "setup-04-confirm",
          title: "시작일과 종료일을 확인해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "설정할 이용기간을 다시 확인하고 확인을 눌러요.",
          result: "센터의 이용기간이 저장돼요.",
          duration: 6500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-04-confirm.jpg",
          alt: "운영관리자(manualsuper) · 시작일과 종료일을 확인해요. 설정할 이용기간을 다시 확인하고 확인을 눌러요.",
          hotspot: {
            x: 0.5116279069767442,
            y: 0.5835416666666666,
            w: 0.3930232558139535,
            h: 0.05555555555555555,
            label: "시작일과 종료일 확인",
          },
        },
        {
          id: "setup-05",
          title: "관리자 지정을 시작해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "새 센터의 관리자 지정을 눌러요.",
          result: "센터 운영을 맡을 계정을 선택할 수 있어요.",
          duration: 6500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-05.jpg",
          alt: "운영관리자(manualsuper) · 관리자 지정을 시작해요. 새 센터의 관리자 지정을 눌러요.",
          hotspot: {
            x: 0.06744186046511629,
            y: 0.8425,
            w: 0.4011627906976744,
            h: 0.05555555555555555,
            label: "센터 관리자 지정",
          },
        },
        {
          id: "setup-06",
          title: "관리할 사람을 찾아요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "이름이나 아이디로 찾아 목록에서 오지훈을 선택해요.",
          result: "회원 정보를 확인하고 센터 관리자로 지정해요.",
          duration: 6500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-06.jpg",
          alt: "운영관리자(manualsuper) · 관리할 사람을 찾아요. 이름이나 아이디로 찾아 목록에서 오지훈을 선택해요.",
          hotspot: {
            x: 0.07674418604651163,
            y: 0.2788888888888889,
            w: 0.8116279069767441,
            h: 0.11333333333333333,
            label: "관리자를 맡을 오지훈 선택",
          },
        },
        {
          id: "setup-07",
          title: "센터 관리자로 지정해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "선택한 계정의 정보를 확인하고 센터 관리자로 지정을 눌러요.",
          result:
            "관리자가 되면 회원 승인과 수강권 발급 등 센터 운영을 맡을 수 있어요.",
          duration: 8000,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-07.jpg",
          alt: "운영관리자(manualsuper) · 센터 관리자로 지정해요. 선택한 계정의 정보를 확인하고 센터 관리자로 지정을 눌러요.",
          hotspot: {
            x: 0.07674418604651163,
            y: 0.7528993055555555,
            w: 0.8465116279069768,
            h: 0.05555555555555555,
            label: "센터 관리자로 지정",
          },
        },
        {
          id: "setup-07-confirm",
          title: "계정과 센터를 확인해요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "오지훈을 재활센터 새봄센터의 관리자로 지정하는지 확인해요.",
          result: "확인을 누르면 관리자 지정이 완료돼요.",
          duration: 6500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-07-confirm.jpg",
          alt: "운영관리자(manualsuper) · 계정과 센터를 확인해요. 오지훈을 재활센터 새봄센터의 관리자로 지정하는지 확인해요.",
          hotspot: {
            x: 0.5116279069767442,
            y: 0.5675520833333333,
            w: 0.3930232558139535,
            h: 0.05555555555555555,
            label: "회원과 센터를 확인하고 지정",
          },
        },
        {
          id: "setup-08",
          title: "센터 운영 준비가 끝났어요",
          role: "SUPER_ADMIN",
          actor: "운영관리자(manualsuper)",
          caption: "센터 카드에 오지훈과 3개월 이용기간이 표시됐어요.",
          result: "이제 지정된 관리자 계정으로 확인해 볼게요.",
          duration: 6500,
          transition: "",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-08.jpg",
          alt: "운영관리자(manualsuper) · 센터 운영 준비가 끝났어요. 센터 카드에 오지훈과 3개월 이용기간이 표시됐어요.",
          hotspot: null,
        },
        {
          id: "setup-09",
          title: "지정된 관리자로 접속해요",
          role: "ADMIN",
          actor: "오지훈(manualcandidate)",
          caption:
            "오지훈 계정으로 다시 로그인했어요. 새 센터의 회원 관리 화면이 열렸어요.",
          result: "이 센터의 관리 업무를 시작할 수 있어요.",
          duration: 8000,
          transition: "이제 센터 관리자 오지훈의 화면이에요.",
          centerName: "재활센터 새봄센터",
          image: "assets/setup-09.jpg",
          alt: "오지훈(manualcandidate) · 지정된 관리자로 접속해요. 오지훈 계정으로 다시 로그인했어요. 새 센터의 회원 관리 화면이 열렸어요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "join-center",
      title: "센터 가입 신청과 승인",
      summary: "회원의 가입 신청부터 관리자의 승인, 센터 입장까지 따라가요.",
      roles: ["CUSTOMER", "ADMIN"],
      category: "센터 이용",
      minutes: 2,
      featured: false,
      prerequisites: [
        "회원가입을 마친 계정이 있어요.",
        "가입할 센터가 이용 중인 상태예요.",
      ],
      outcome:
        "김지우가 센터 가입 승인을 받고 자신의 일정 화면으로 들어갔어요.",
      promoStepIds: ["join-01", "join-02", "join-03", "join-04", "join-06"],
      steps: [
        {
          id: "join-01",
          title: "이용할 센터를 찾아요",
          role: "CUSTOMER",
          actor: "김지우(manualjiwoo)",
          caption: "김지우가 재활센터 시연센터를 찾았어요. 가입 신청을 눌러요.",
          result: "아직 센터에 가입하기 전인 회원의 화면이에요.",
          duration: 6500,
          transition: "",
          image: "assets/join-01.jpg",
          alt: "김지우(manualjiwoo) · 이용할 센터를 찾아요. 김지우가 재활센터 시연센터를 찾았어요. 가입 신청을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.7511627906976744,
            x: 0.10697674418604654,
            y: 0.7735069444444445,
            label: "재활센터 시연센터 가입 신청",
          },
        },
        {
          id: "join-02-confirm",
          title: "가입 신청을 확인해요",
          role: "CUSTOMER",
          actor: "김지우(manualjiwoo)",
          caption: "신청할 센터가 맞는지 보고 확인을 눌러요.",
          result: "센터 관리자가 회원 정보를 확인할 수 있도록 신청해요.",
          duration: 6500,
          transition: "",
          image: "assets/join-02-confirm.jpg",
          alt: "김지우(manualjiwoo) · 가입 신청을 확인해요. 신청할 센터가 맞는지 보고 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.39302325581395353,
            x: 0.49418604651162795,
            y: 0.5835416666666666,
            label: "가입 신청 확인",
          },
        },
        {
          id: "join-02",
          title: "가입 승인을 기다려요",
          role: "CUSTOMER",
          actor: "김지우(manualjiwoo)",
          caption: "신청한 센터에 승인 대기가 표시됐어요.",
          result: "관리자가 승인하면 이 센터를 이용할 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/join-02.jpg",
          alt: "김지우(manualjiwoo) · 가입 승인을 기다려요. 신청한 센터에 승인 대기가 표시됐어요.",
          hotspot: null,
        },
        {
          id: "join-03",
          title: "관리자가 신청을 확인해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption:
            "가입 신청 목록에서 김지우의 이름과 아이디를 확인하고 가입 승인을 눌러요.",
          result: "승인할 회원을 한 번 더 확인해요.",
          duration: 6500,
          transition: "센터 관리자 박지은의 화면이에요.",
          image: "assets/join-03.jpg",
          alt: "박지은(manualmanager) · 관리자가 신청을 확인해요. 가입 신청 목록에서 김지우의 이름과 아이디를 확인하고 가입 승인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.4908430232558141,
            x: 0.3974927325581395,
            y: 0.55265625,
            label: "김지우 가입 승인",
          },
        },
        {
          id: "join-04",
          title: "센터 가입을 승인해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "확인창에서 김지우가 맞는지 보고 확인을 눌러요.",
          result: "김지우가 이 센터의 회원이 돼요.",
          duration: 6500,
          transition: "",
          image: "assets/join-04.jpg",
          alt: "박지은(manualmanager) · 센터 가입을 승인해요. 확인창에서 김지우가 맞는지 보고 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.39302325581395353,
            x: 0.49418604651162795,
            y: 0.5675520833333333,
            label: "회원 승인 확인",
          },
        },
        {
          id: "join-05",
          title: "가입한 센터로 들어가요",
          role: "CUSTOMER",
          actor: "김지우(manualjiwoo)",
          caption:
            "김지우 계정으로 다시 확인했어요. 가입한 센터에서 내 수업 일정 보기를 눌러요.",
          result: "승인된 센터의 내 일정으로 이동해요.",
          duration: 6500,
          transition: "다시 회원 김지우의 화면이에요.",
          image: "assets/join-05.jpg",
          alt: "김지우(manualjiwoo) · 가입한 센터로 들어가요. 김지우 계정으로 다시 확인했어요. 가입한 센터에서 내 수업 일정 보기를 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.7511627906976744,
            x: 0.10697674418604654,
            y: 0.6188715277777778,
            label: "내 수업 일정 보기",
          },
        },
        {
          id: "join-06",
          title: "내 일정 화면이 열렸어요",
          role: "CUSTOMER",
          actor: "김지우(manualjiwoo)",
          caption:
            "센터 입장을 마쳤어요. 앞으로 예약한 수업과 수강권을 이곳에서 확인할 수 있어요.",
          result:
            "수강권 발급과 수업 예약은 센터 관리자와 운동지도자가 진행해요.",
          duration: 6500,
          transition: "",
          image: "assets/join-06.jpg",
          alt: "김지우(manualjiwoo) · 내 일정 화면이 열렸어요. 센터 입장을 마쳤어요. 앞으로 예약한 수업과 수강권을 이곳에서 확인할 수 있어요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "lesson-pass",
      title: "수강권 발급과 회원 확인",
      summary: "관리자가 발급한 수강권을 회원 화면에서 확인해요.",
      roles: ["CUSTOMER", "ADMIN"],
      category: "수강권",
      minutes: 2,
      featured: false,
      prerequisites: [
        "센터 가입이 승인된 회원이 있어요.",
        "센터 관리자가 발급할 수강권 이름과 횟수를 확인해요.",
      ],
      outcome:
        "한도윤에게 개인 수업 10회 수강권이 발급되고, 회원도 남은 횟수를 확인할 수 있어요.",
      promoStepIds: ["pass-00", "pass-02", "pass-03-confirm", "pass-04"],
      steps: [
        {
          id: "pass-00",
          title: "아직 수강권이 없어요",
          role: "CUSTOMER",
          actor: "한도윤(manualcredit)",
          caption:
            "한도윤의 수강권은 현재 0회예요. 새 수강권이 추가되는 과정을 살펴볼게요.",
          result: "발급 전 상태를 먼저 확인해요.",
          duration: 6500,
          transition: "",
          image: "assets/pass-00.jpg",
          alt: "한도윤(manualcredit) · 아직 수강권이 없어요. 한도윤의 수강권은 현재 0회예요. 새 수강권이 추가되는 과정을 살펴볼게요.",
          hotspot: null,
        },
        {
          id: "pass-01",
          title: "발급할 회원을 찾아요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "관리자의 회원 목록에서 한도윤을 선택해요.",
          result: "이름과 아이디를 확인한 뒤 수강권을 발급해요.",
          duration: 6500,
          transition: "센터 관리자 박지은의 화면으로 바뀌었어요.",
          image: "assets/pass-01.jpg",
          alt: "박지은(manualmanager) · 발급할 회원을 찾아요. 관리자의 회원 목록에서 한도윤을 선택해요.",
          hotspot: {
            h: 0.11333333333333331,
            w: 0.9441860465116279,
            x: 0.02790697674418605,
            y: 0.3277777777777778,
            label: "한도윤 회원 선택",
          },
        },
        {
          id: "pass-02",
          title: "수강권 내용을 입력해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption:
            "수강권 이름은 개인 수업 10회, 횟수는 10회로 입력했어요. 발급 사유도 적고 발급을 눌러요.",
          result: "입력한 이름과 횟수를 다시 확인해요.",
          duration: 8000,
          transition: "",
          image: "assets/pass-02.jpg",
          alt: "박지은(manualmanager) · 수강권 내용을 입력해요. 수강권 이름은 개인 수업 10회, 횟수는 10회로 입력했어요. 발급 사유도 적고 발급을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.7325581395348837,
            x: 0.11627906976744186,
            y: 0.5825694444444445,
            label: "수강권 발급",
          },
        },
        {
          id: "pass-03-confirm",
          title: "발급 내용을 확인해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "대상 회원과 수강권 내용을 확인하고 확인을 눌러요.",
          result: "선택한 회원에게 수강권이 발급돼요.",
          duration: 6500,
          transition: "",
          image: "assets/pass-03-confirm.jpg",
          alt: "박지은(manualmanager) · 발급 내용을 확인해요. 대상 회원과 수강권 내용을 확인하고 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3930232558139535,
            x: 0.5116279069767442,
            y: 0.6155381944444445,
            label: "발급 내용 확인",
          },
        },
        {
          id: "pass-03",
          title: "수강권이 추가됐어요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "관리자의 회원 정보에서 발급한 수강권을 확인할 수 있어요.",
          result: "이제 회원 계정에서도 확인해 볼게요.",
          duration: 6500,
          transition: "",
          image: "assets/pass-03.jpg",
          alt: "박지은(manualmanager) · 수강권이 추가됐어요. 관리자의 회원 정보에서 발급한 수강권을 확인할 수 있어요.",
          hotspot: null,
        },
        {
          id: "pass-04",
          title: "회원도 수강권을 확인해요",
          role: "CUSTOMER",
          actor: "한도윤(manualcredit)",
          caption:
            "한도윤 계정으로 다시 확인했어요. 남은 수업 10회, 예약된 수업 0회, 새로 예약 가능 10회예요.",
          result: "수강권 내역에서 발급받은 수강권과 남은 횟수를 볼 수 있어요.",
          duration: 8500,
          transition: "회원 한도윤의 화면이에요.",
          image: "assets/pass-04.jpg",
          alt: "한도윤(manualcredit) · 회원도 수강권을 확인해요. 한도윤 계정으로 다시 확인했어요. 남은 수업 10회, 예약된 수업 0회, 새로 예약 가능 10회예요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "appoint-instructor",
      title: "회원에서 운동지도자로",
      summary:
        "관리자가 임명하면 같은 계정에서 어떤 화면을 사용하게 되는지 살펴봐요.",
      roles: ["CUSTOMER", "ADMIN", "STAFF"],
      category: "역할과 권한",
      minutes: 2,
      featured: true,
      prerequisites: [
        "같은 센터에 가입이 승인된 회원이 있어요.",
        "센터 관리자가 임명할 수 있어요.",
      ],
      outcome:
        "김하늘의 계정은 그대로예요. 이 센터에서는 운동지도자로 일정과 회원을 확인할 수 있어요.",
      promoStepIds: [
        "role-01",
        "role-02",
        "role-03-confirm",
        "role-03-result",
        "role-04",
      ],
      steps: [
        {
          id: "role-01",
          title: "지금은 회원 화면이에요",
          role: "CUSTOMER",
          actor: "김하늘(manualhaneul)",
          caption:
            "김하늘은 현재 이 센터의 회원이에요. 임명 전 화면부터 살펴볼게요.",
          result: "내 수업 일정과 수강권을 확인하는 회원 화면이에요.",
          duration: 6500,
          transition: "",
          image: "assets/role-01.jpg",
          alt: "김하늘(manualhaneul) · 지금은 회원 화면이에요. 김하늘은 현재 이 센터의 회원이에요. 임명 전 화면부터 살펴볼게요.",
          hotspot: null,
        },
        {
          id: "role-02-list",
          title: "임명할 회원을 찾아요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption:
            "관리자의 회원 목록에서 김하늘을 선택해요. 이름과 아이디를 함께 확인하세요.",
          result: "이제 선택한 회원의 정보를 확인해요.",
          duration: 6500,
          transition: "센터 관리자 박지은의 화면으로 바뀌었어요.",
          image: "assets/role-02-list.jpg",
          alt: "박지은(manualmanager) · 임명할 회원을 찾아요. 관리자의 회원 목록에서 김하늘을 선택해요. 이름과 아이디를 함께 확인하세요.",
          hotspot: {
            h: 0.11333333333333331,
            w: 0.9441860465116279,
            x: 0.02790697674418605,
            y: 0.7077777777777777,
            label: "김하늘 회원 선택",
          },
        },
        {
          id: "role-02",
          title: "운동지도자로 임명해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "김하늘의 정보에서 운동지도자로 임명을 눌러요.",
          result: "이 센터의 역할을 바꾸기 전에 확인창이 열려요.",
          duration: 6500,
          transition: "",
          image: "assets/role-02.jpg",
          alt: "박지은(manualmanager) · 운동지도자로 임명해요. 김하늘의 정보에서 운동지도자로 임명을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.8116279069767441,
            x: 0.07674418604651163,
            y: 0.3206597222222222,
            label: "운동지도자로 임명",
          },
        },
        {
          id: "role-03-confirm",
          title: "대상 계정을 확인해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "이름과 아이디를 다시 확인하고 확인을 눌러요.",
          result: "김하늘을 이 센터의 운동지도자로 임명해요.",
          duration: 6500,
          transition: "",
          image: "assets/role-03-confirm.jpg",
          alt: "박지은(manualmanager) · 대상 계정을 확인해요. 이름과 아이디를 다시 확인하고 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3930232558139535,
            x: 0.5116279069767442,
            y: 0.5675520833333333,
            label: "임명 확인",
          },
        },
        {
          id: "role-03-result",
          title: "관리자에게도 새 역할이 보여요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption:
            "회원 정보가 지도자 정보로 바뀌었어요. 임명이 완료된 상태예요.",
          result: "기존 계정을 유지하며 이 센터의 역할이 바뀌었어요.",
          duration: 6500,
          transition: "",
          image: "assets/role-03-result.jpg",
          alt: "박지은(manualmanager) · 관리자에게도 새 역할이 보여요. 회원 정보가 지도자 정보로 바뀌었어요. 임명이 완료된 상태예요.",
          hotspot: null,
        },
        {
          id: "role-04",
          title: "같은 계정으로 다시 확인해요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption:
            "김하늘 계정으로 다시 접속했어요. 지도자의 일정과 회원 메뉴를 사용할 수 있어요.",
          result:
            "역할은 센터별로 적용돼요. 이 장면은 다시 접속해 확인한 결과예요.",
          duration: 8000,
          transition: "이제 임명된 김하늘의 화면을 확인해요.",
          image: "assets/role-04.jpg",
          alt: "김하늘(manualhaneul) · 같은 계정으로 다시 확인해요. 김하늘 계정으로 다시 접속했어요. 지도자의 일정과 회원 메뉴를 사용할 수 있어요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "book-lesson",
      title: "예약하고 회원이 확인하기",
      summary: "지도자가 잡은 수업을 회원의 일정에서 함께 확인해요.",
      roles: ["CUSTOMER", "STAFF"],
      category: "수업 예약",
      minutes: 3,
      featured: true,
      prerequisites: [
        "회원의 센터 가입이 승인되어 있어요.",
        "예약할 수 있는 수강권 횟수와 비어 있는 시간이 있어요.",
      ],
      outcome:
        "김하늘이 예약한 9월 28일 오후 2시 수업이 이서준의 일정에도 표시돼요.",
      promoStepIds: [
        "book-01",
        "book-03",
        "book-04",
        "book-05-confirm",
        "book-06-summary",
        "book-06",
      ],
      steps: [
        {
          id: "book-01",
          title: "예약 전 횟수를 살펴봐요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "이서준은 남은 수업 9회 중 1회가 예약되어 있어요. 새로 예약할 수 있는 횟수는 8회예요.",
          result: "이 상태에서 새 수업 한 번을 예약해 볼게요.",
          duration: 7500,
          transition: "",
          image: "assets/book-01.jpg",
          alt: "이서준(manualseojun) · 예약 전 횟수를 살펴봐요. 이서준은 남은 수업 9회 중 1회가 예약되어 있어요. 새로 예약할 수 있는 횟수는 8회예요.",
          hotspot: null,
        },
        {
          id: "book-02-date",
          title: "수업할 날짜를 골라요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "지도자의 달력에서 9월 28일을 선택해요.",
          result: "고른 날짜에 예약을 등록할 수 있어요.",
          duration: 6500,
          transition: "운동지도자 김하늘의 화면으로 바뀌었어요.",
          image: "assets/book-02-date.jpg",
          alt: "김하늘(manualhaneul) · 수업할 날짜를 골라요. 지도자의 달력에서 9월 28일을 선택해요.",
          hotspot: {
            h: 0.05286458333333333,
            w: 0.1106468023255814,
            x: 0.1873546511627907,
            y: 0.6576562499999999,
            label: "9월 28일 선택",
          },
        },
        {
          id: "book-02",
          title: "예약 등록을 열어요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "날짜 아래 예약 등록을 눌러요.",
          result: "회원과 시간을 입력하는 창이 열려요.",
          duration: 6500,
          transition: "",
          image: "assets/book-02.jpg",
          alt: "김하늘(manualhaneul) · 예약 등록을 열어요. 날짜 아래 예약 등록을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.20763081395348837,
            x: 0.6900436046511628,
            y: 0.8838368055555555,
            label: "예약 등록 열기",
          },
        },
        {
          id: "book-03",
          title: "수업할 회원을 선택해요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption:
            "회원 목록에서 이서준을 골라요. 예약 가능한 횟수도 확인해요.",
          result: "선택한 회원의 수강권을 확인한 뒤 시간을 정해요.",
          duration: 6500,
          transition: "",
          image: "assets/book-03.jpg",
          alt: "김하늘(manualhaneul) · 수업할 회원을 선택해요. 회원 목록에서 이서준을 골라요. 예약 가능한 횟수도 확인해요.",
          hotspot: {
            h: 0.057777777777777775,
            w: 0.8465116279069768,
            x: 0.07674418604651163,
            y: 0.3893923611111111,
            label: "예약할 회원 선택",
          },
        },
        {
          id: "book-04-time",
          title: "시작 시각을 정해요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "오후 2시를 고르고 선택 완료를 눌러요.",
          result: "이 센터의 기본 수업 시간 60분에 맞춰 종료 시각이 채워져요.",
          duration: 6500,
          transition: "",
          image: "assets/book-04-time.jpg",
          alt: "김하늘(manualhaneul) · 시작 시각을 정해요. 오후 2시를 고르고 선택 완료를 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.7325581395348837,
            x: 0.11627906976744186,
            y: 0.8046354166666667,
            label: "14시 선택 완료",
          },
        },
        {
          id: "book-04",
          title: "예약 내용을 살펴봐요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption:
            "9월 28일 오후 2시부터 3시까지, 이서준의 수업인지 확인하고 예약 등록을 눌러요.",
          result: "날짜와 시간을 한 번 더 확인해요.",
          duration: 7500,
          transition: "",
          image: "assets/book-04.jpg",
          alt: "김하늘(manualhaneul) · 예약 내용을 살펴봐요. 9월 28일 오후 2시부터 3시까지, 이서준의 수업인지 확인하고 예약 등록을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.8465116279069768,
            x: 0.07674418604651163,
            y: 0.7333159722222222,
            label: "예약 등록",
          },
        },
        {
          id: "book-05-confirm",
          title: "예약을 확정해요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "확인창의 수업 일시를 보고 확인을 눌러요.",
          result: "예약 가능한 수강권이 자동으로 적용돼요.",
          duration: 6500,
          transition: "",
          image: "assets/book-05-confirm.jpg",
          alt: "김하늘(manualhaneul) · 예약을 확정해요. 확인창의 수업 일시를 보고 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3930232558139535,
            x: 0.5116279069767442,
            y: 0.5675520833333333,
            label: "예약 내용 확인",
          },
        },
        {
          id: "book-05",
          title: "지도자 일정에 생겼어요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "선택한 날짜에 이서준의 수업이 표시됐어요.",
          result: "이제 회원 화면에서 같은 예약을 확인해 볼게요.",
          duration: 6500,
          transition: "",
          image: "assets/book-05.jpg",
          alt: "김하늘(manualhaneul) · 지도자 일정에 생겼어요. 선택한 날짜에 이서준의 수업이 표시됐어요.",
          hotspot: {
            h: 0.10555555555555556,
            w: 0.8302325581395349,
            x: 0.06744186046511629,
            y: 0.7980555555555555,
            label: "등록된 예약 확인",
          },
        },
        {
          id: "book-06-summary",
          title: "회원의 횟수를 다시 확인해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "회원 화면을 다시 불러왔어요. 남은 수업은 9회, 예약된 수업은 2회, 새로 예약 가능은 7회예요.",
          result:
            "예약만으로 수업이 차감되지는 않아요. 수업 완료 때 1회가 차감돼요.",
          duration: 9000,
          transition: "이제 회원 이서준의 화면을 확인해요.",
          image: "assets/book-06-summary.jpg",
          alt: "이서준(manualseojun) · 회원의 횟수를 다시 확인해요. 회원 화면을 다시 불러왔어요. 남은 수업은 9회, 예약된 수업은 2회, 새로 예약 가능은 7회예요.",
          hotspot: null,
        },
        {
          id: "book-06",
          title: "회원에게도 같은 수업이 보여요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "9월 28일을 열면 김하늘 선생님의 오후 2시부터 3시까지 수업을 볼 수 있어요.",
          result:
            "회원은 자신의 일정을 확인해요. 변경이 필요하면 선생님께 알려 주세요.",
          duration: 8000,
          transition: "",
          image: "assets/book-06.jpg",
          alt: "이서준(manualseojun) · 회원에게도 같은 수업이 보여요. 9월 28일을 열면 김하늘 선생님의 오후 2시부터 3시까지 수업을 볼 수 있어요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "change-reservation",
      title: "시간 변경과 예약 취소",
      summary:
        "같은 예약의 시간을 바꾸고, 취소한 뒤 회원 화면의 결과를 확인해요.",
      roles: ["STAFF", "CUSTOMER"],
      category: "수업 예약",
      minutes: 2,
      featured: false,
      prerequisites: [
        "아직 진행 전인 예약이 있어요.",
        "지도자가 변경할 수업의 날짜와 시간을 확인해요.",
      ],
      outcome:
        "시간 변경과 취소 결과가 회원 일정에도 표시되고, 취소한 예약의 가능 횟수가 돌아와요.",
      promoStepIds: [
        "change-01",
        "change-02",
        "change-03",
        "change-04-confirm",
        "change-05-summary",
        "change-05",
      ],
      steps: [
        {
          id: "change-01",
          title: "변경할 수업을 열어요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "이서준의 예약 상세에서 시간 변경을 눌러요.",
          result: "기존 날짜와 시간을 바탕으로 변경할 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/change-01.jpg",
          alt: "김하늘(manualhaneul) · 변경할 수업을 열어요. 이서준의 예약 상세에서 시간 변경을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3720930232558139,
            x: 0.11627906976744186,
            y: 0.8372916666666667,
            label: "시간 변경",
          },
        },
        {
          id: "change-02",
          title: "새 시간을 저장해요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "같은 날 오후 3시부터 4시까지로 바꾼 뒤 변경 저장을 눌러요.",
          result: "저장 전 변경할 일시를 확인해요.",
          duration: 6500,
          transition: "",
          image: "assets/change-02.jpg",
          alt: "김하늘(manualhaneul) · 새 시간을 저장해요. 같은 날 오후 3시부터 4시까지로 바꾼 뒤 변경 저장을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.4116279069767442,
            x: 0.5116279069767442,
            y: 0.8384722222222222,
            label: "변경 저장",
          },
        },
        {
          id: "change-02-confirm",
          title: "변경 전후를 확인해요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "기존 시간과 새 시간을 확인한 뒤 확인을 눌러요.",
          result: "같은 예약의 시간이 오후 3시부터 4시까지로 바뀌어요.",
          duration: 6500,
          transition: "",
          image: "assets/change-02-confirm.jpg",
          alt: "김하늘(manualhaneul) · 변경 전후를 확인해요. 기존 시간과 새 시간을 확인한 뒤 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3930232558139535,
            x: 0.5116279069767442,
            y: 0.5835416666666666,
            label: "변경 내용 확인",
          },
        },
        {
          id: "change-03",
          title: "회원도 새 시간을 확인해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "회원 화면을 다시 불러왔어요. 김하늘 선생님의 수업 시간이 오후 3시부터 4시까지로 바뀌었어요.",
          result: "회원은 바뀐 날짜와 시간을 확인할 수 있어요.",
          duration: 8000,
          transition: "회원 이서준의 화면으로 바뀌었어요.",
          image: "assets/change-03.jpg",
          alt: "이서준(manualseojun) · 회원도 새 시간을 확인해요. 회원 화면을 다시 불러왔어요. 김하늘 선생님의 수업 시간이 오후 3시부터 4시까지로 바뀌었어요.",
          hotspot: null,
        },
        {
          id: "change-04",
          title: "예약을 취소할 수 있어요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "같은 예약을 열고 예약 취소를 눌러요.",
          result: "취소 전 수업 일시와 회원을 다시 확인해요.",
          duration: 6500,
          transition: "다시 운동지도자 김하늘의 화면이에요.",
          image: "assets/change-04.jpg",
          alt: "김하늘(manualhaneul) · 예약을 취소할 수 있어요. 같은 예약을 열고 예약 취소를 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3720930232558139,
            x: 0.5116279069767442,
            y: 0.8372916666666667,
            label: "예약 취소",
          },
        },
        {
          id: "change-04-confirm",
          title: "취소 내용을 확인해요",
          role: "STAFF",
          actor: "김하늘(manualhaneul)",
          caption: "취소할 수업을 확인하고 확인을 눌러요.",
          result: "수업 횟수를 차감하지 않고 예약을 취소해요.",
          duration: 6500,
          transition: "",
          image: "assets/change-04-confirm.jpg",
          alt: "김하늘(manualhaneul) · 취소 내용을 확인해요. 취소할 수업을 확인하고 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3930232558139535,
            x: 0.5116279069767442,
            y: 0.5835416666666666,
            label: "취소 확인",
          },
        },
        {
          id: "change-05-summary",
          title: "예약 가능 횟수가 돌아왔어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "다시 불러온 회원 화면에서 남은 수업 9회, 예약된 수업 1회, 새로 예약 가능 8회를 확인해요.",
          result: "취소한 예약 한 번만큼 다시 예약할 수 있어요.",
          duration: 8000,
          transition: "회원 이서준의 결과를 확인해요.",
          image: "assets/change-05-summary.jpg",
          alt: "이서준(manualseojun) · 예약 가능 횟수가 돌아왔어요. 다시 불러온 회원 화면에서 남은 수업 9회, 예약된 수업 1회, 새로 예약 가능 8회를 확인해요.",
          hotspot: null,
        },
        {
          id: "change-05",
          title: "취소 기록도 확인해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "해당 날짜의 수업 상세에는 취소 표시가 남아 있어요.",
          result: "취소된 수업을 예약된 수업과 구분해 볼 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/change-05.jpg",
          alt: "이서준(manualseojun) · 취소 기록도 확인해요. 해당 날짜의 수업 상세에는 취소 표시가 남아 있어요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "share-record",
      title: "수업 메모와 이야기 나누기",
      summary: "끝난 수업을 기록하고, 회원과 메모를 나눈 뒤 이야기를 이어가요.",
      roles: ["STAFF", "CUSTOMER"],
      category: "운동 기록",
      minutes: 3,
      featured: true,
      prerequisites: [
        "종료 시간이 지난 예약이 있어요.",
        "수업을 완료한 지도자가 기록을 남겨요.",
      ],
      outcome:
        "윤서연이 공유한 메모를 이서준이 읽고, 같은 수업의 대화로 이야기를 남겼어요.",
      promoStepIds: [
        "record-01-confirm",
        "record-03",
        "record-04-confirm",
        "record-05",
        "record-06",
        "record-07",
      ],
      steps: [
        {
          id: "record-01",
          title: "끝난 수업을 완료해요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption:
            "9월 26일 오전 10시 이서준의 수업이 끝났어요. 수업 완료를 눌러요.",
          result: "종료 시간이 지난 수업만 완료할 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/record-01.jpg",
          alt: "윤서연(manualteacher) · 끝난 수업을 완료해요. 9월 26일 오전 10시 이서준의 수업이 끝났어요. 수업 완료를 눌러요.",
          hotspot: {
            h: 0.05644097222222222,
            w: 0.7674418604651163,
            x: 0.11627906976744186,
            y: 0.7469097222222222,
            label: "수업 완료",
          },
        },
        {
          id: "record-01-confirm",
          title: "1회 사용을 확인해요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption: "수업과 차감할 횟수를 확인한 뒤 확인을 눌러요.",
          result: "남은 수업이 9회에서 8회로 바뀌어요.",
          duration: 6500,
          transition: "",
          image: "assets/record-01-confirm.jpg",
          alt: "윤서연(manualteacher) · 1회 사용을 확인해요. 수업과 차감할 횟수를 확인한 뒤 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3930232558139535,
            x: 0.5116279069767442,
            y: 0.5995486111111111,
            label: "완료와 1회 사용 확인",
          },
        },
        {
          id: "record-02-open",
          title: "지도 기록을 열어요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption: "완료한 수업에서 지도 기록 열기를 눌러요.",
          result: "수업 기록과 메모를 남기는 창이 열려요.",
          duration: 6500,
          transition: "",
          image: "assets/record-02-open.jpg",
          alt: "윤서연(manualteacher) · 지도 기록을 열어요. 완료한 수업에서 지도 기록 열기를 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.7325581395348837,
            x: 0.11627906976744186,
            y: 0.8249305555555555,
            label: "지도 기록 열기",
          },
        },
        {
          id: "record-02",
          title: "첫 메모를 남겨요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption: "밝은 메모 영역을 누르면 글을 쓸 수 있어요.",
          result: "오늘 수업에서 기억할 내용을 적어 보세요.",
          duration: 6500,
          transition: "",
          image: "assets/record-02.jpg",
          alt: "윤서연(manualteacher) · 첫 메모를 남겨요. 밝은 메모 영역을 누르면 글을 쓸 수 있어요.",
          hotspot: {
            h: 0.25265625,
            w: 0.8465116279069768,
            x: 0.07674418604651163,
            y: 0.4728819444444444,
            label: "첫 메모 남기기",
          },
        },
        {
          id: "record-03",
          title: "회원과 공유를 켜요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption:
            "메모를 작성하고 회원과 공유를 켰어요. 공유할 메모인지 다시 확인해요.",
          result:
            "공유를 켠 메모만 회원이 볼 수 있어요. 새 메모는 처음에 나만 보는 상태예요.",
          duration: 8000,
          transition: "",
          image: "assets/record-03.jpg",
          alt: "윤서연(manualteacher) · 회원과 공유를 켜요. 메모를 작성하고 회원과 공유를 켰어요. 공유할 메모인지 다시 확인해요.",
          hotspot: {
            h: 0.04888888888888889,
            w: 0.10232558139534884,
            x: 0.7372093023255814,
            y: 0.4883854166666667,
            label: "회원과 공유 설정 확인",
          },
        },
        {
          id: "record-04-save",
          title: "기록 저장을 눌러요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption: "작성한 내용을 살펴보고 기록 저장을 눌러요.",
          result: "어떤 메모를 회원과 공유하는지 확인창이 열려요.",
          duration: 6500,
          transition: "",
          image: "assets/record-04-save.jpg",
          alt: "윤서연(manualteacher) · 기록 저장을 눌러요. 작성한 내용을 살펴보고 기록 저장을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.46667877906976746,
            x: 0.3775072674418605,
            y: 0.8244791666666667,
            label: "기록 저장",
          },
        },
        {
          id: "record-04-confirm",
          title: "공유할 메모를 확인해요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption: "메모 1장을 회원과 공유하는지 확인하고 확인을 눌러요.",
          result: "메모가 저장되어 회원에게 보여요.",
          duration: 6500,
          transition: "",
          image: "assets/record-04-confirm.jpg",
          alt: "윤서연(manualteacher) · 공유할 메모를 확인해요. 메모 1장을 회원과 공유하는지 확인하고 확인을 눌러요.",
          hotspot: {
            h: 0.05555555555555555,
            w: 0.3930232558139535,
            x: 0.5116279069767442,
            y: 0.5675520833333333,
            label: "공유 기록 저장 확인",
          },
        },
        {
          id: "record-04",
          title: "메모가 저장됐어요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption:
            "작성한 글이 수업 기록에 남았어요. 메모 편집으로 다시 고칠 수 있어요.",
          result: "이제 회원 화면에서 같은 메모를 확인해 볼게요.",
          duration: 6500,
          transition: "",
          image: "assets/record-04.jpg",
          alt: "윤서연(manualteacher) · 메모가 저장됐어요. 작성한 글이 수업 기록에 남았어요. 메모 편집으로 다시 고칠 수 있어요.",
          hotspot: null,
        },
        {
          id: "record-05-list",
          title: "회원의 운동 기록을 살펴봐요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "회원 계정으로 다시 확인했어요. 메모가 있는 오전 10시 수업의 메모 확인을 눌러요.",
          result:
            "다른 완료 수업에 공유 메모가 없으면 아직 남겨진 메모가 없다고 안내해요.",
          duration: 8000,
          transition: "회원 이서준의 화면으로 바뀌었어요.",
          image: "assets/record-05-list.jpg",
          alt: "이서준(manualseojun) · 회원의 운동 기록을 살펴봐요. 회원 계정으로 다시 확인했어요. 메모가 있는 오전 10시 수업의 메모 확인을 눌러요.",
          hotspot: {
            h: 0.23776041666666667,
            w: 0.8488372093023255,
            x: 0.05813953488372093,
            y: 0.7525000000000001,
            label: "공유 메모 확인",
          },
        },
        {
          id: "record-05",
          title: "선생님의 메모를 읽어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "윤서연 선생님이 공유한 메모를 확인해요.",
          result: "회원에게는 공유된 메모만 보여요.",
          duration: 6500,
          transition: "",
          image: "assets/record-05.jpg",
          alt: "이서준(manualseojun) · 선생님의 메모를 읽어요. 윤서연 선생님이 공유한 메모를 확인해요.",
          hotspot: null,
        },
        {
          id: "record-06-input",
          title: "선생님께 이야기를 보내요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "앞서 메모를 읽었다고 인사했어요. 이번에는 “다음 수업 때 궁금한 점을 여쭤볼게요!”라고 적고 보내기를 눌러요.",
          result: "이전 이야기에 이어 메시지를 더 남길 수 있어요.",
          duration: 8500,
          transition: "",
          image: "assets/record-06-input.jpg",
          alt: "이서준(manualseojun) · 선생님께 이야기를 보내요. 앞서 메모를 읽었다고 인사했어요. 이번에는 “다음 수업 때 궁금한 점을 여쭤볼게요!”라고 적고 보내기를 눌러요.",
          hotspot: {
            x: 0.649672965116279,
            y: 0.8414583333333333,
            w: 0.16893168604651163,
            h: 0.05333333333333334,
            label: "선생님께 메시지 보내기",
          },
        },
        {
          id: "record-06-confirm",
          title: "메시지 보내기를 확인해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "궁금한 점을 다음 수업에서 물어보겠다는 메시지를 보낼지 확인해요.",
          result: "확인을 누르면 같은 수업의 대화에 새 메시지가 저장돼요.",
          duration: 6500,
          transition: "",
          image: "assets/record-06-confirm.jpg",
          alt: "이서준(manualseojun) · 메시지 보내기를 확인해요. 궁금한 점을 다음 수업에서 물어보겠다는 메시지를 보낼지 확인해요.",
          hotspot: {
            x: 0.5116279069767442,
            y: 0.5515451388888889,
            w: 0.3930232558139535,
            h: 0.05555555555555555,
            label: "메시지 보내기 확인",
          },
        },
        {
          id: "record-06",
          title: "새 메시지가 남았어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "“다음 수업 때 궁금한 점을 여쭤볼게요!”가 오른쪽 말풍선에 추가됐어요.",
          result: "앞서 보낸 인사와 새 메시지를 함께 확인할 수 있어요.",
          duration: 7500,
          transition: "",
          image: "assets/record-06.jpg",
          alt: "이서준(manualseojun) · 새 메시지가 남았어요. “다음 수업 때 궁금한 점을 여쭤볼게요!”가 오른쪽 말풍선에 추가됐어요.",
          hotspot: null,
        },
        {
          id: "record-07",
          title: "선생님도 이야기를 확인해요",
          role: "STAFF",
          actor: "윤서연(manualteacher)",
          caption:
            "지도자 계정에서 같은 기록을 다시 열었어요. 회원의 인사와 새로 보낸 메시지를 확인할 수 있어요.",
          result: "공유한 메모와 대화가 한 수업의 기록으로 이어져요.",
          duration: 8000,
          transition: "이제 운동지도자 윤서연의 화면이에요.",
          image: "assets/record-07.jpg",
          alt: "윤서연(manualteacher) · 선생님도 이야기를 확인해요. 지도자 계정에서 같은 기록을 다시 열었어요. 회원의 인사와 새로 보낸 메시지를 확인할 수 있어요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "center-news",
      title: "센터 소식과 궁금한 점 찾기",
      summary: "관리자가 공지와 답변을 등록하고 회원이 읽는 과정을 살펴봐요.",
      roles: ["ADMIN", "CUSTOMER"],
      category: "센터 소식",
      minutes: 2,
      featured: false,
      prerequisites: [
        "센터 관리자가 공지와 FAQ를 작성해요.",
        "같은 센터의 회원과 운동지도자가 내용을 확인해요.",
      ],
      outcome:
        "센터 소식은 공지사항에서, 자주 묻는 질문의 답은 FAQ에서 확인할 수 있어요.",
      promoStepIds: [
        "news-02",
        "news-02-confirm",
        "news-03",
        "news-04",
        "news-04-confirm",
        "news-05",
      ],
      steps: [
        {
          id: "news-01",
          title: "센터 소식을 작성해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "공지사항에서 공지 작성을 눌러요.",
          result: "센터에서 전할 소식을 등록할 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/news-01.jpg",
          alt: "박지은(manualmanager) · 센터 소식을 작성해요. 공지사항에서 공지 작성을 눌러요.",
          hotspot: {
            h: 0.05333333333333334,
            w: 0.11162790697674418,
            x: 0.8209302325581396,
            y: 0.16,
            label: "공지 작성",
          },
        },
        {
          id: "news-02",
          title: "대상과 내용을 정해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption:
            "대상을 회원으로 선택하고 센터 이용 안내를 작성했어요. 공지사항 등록을 눌러요.",
          result:
            "회원 대상 공지는 같은 센터의 회원과 운동지도자 모두 볼 수 있어요.",
          duration: 8000,
          transition: "",
          image: "assets/news-02.jpg",
          alt: "박지은(manualmanager) · 대상과 내용을 정해요. 대상을 회원으로 선택하고 센터 이용 안내를 작성했어요. 공지사항 등록을 눌러요.",
          hotspot: {
            x: 0.07674418604651163,
            y: 0.868125,
            w: 0.8465116279069768,
            h: 0.05555555555555555,
            label: "공지사항 등록",
          },
        },
        {
          id: "news-02-confirm",
          title: "공지 등록을 확인해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "안내를 보여줄 대상을 확인하고 확인을 눌러요.",
          result: "센터 공지사항에 새 소식이 등록돼요.",
          duration: 6500,
          transition: "",
          image: "assets/news-02-confirm.jpg",
          alt: "박지은(manualmanager) · 공지 등록을 확인해요. 안내를 보여줄 대상을 확인하고 확인을 눌러요.",
          hotspot: {
            x: 0.5116279069767442,
            y: 0.5677777777777778,
            w: 0.3953488372093023,
            h: 0.056666666666666664,
            label: "공지 등록 확인",
          },
        },
        {
          id: "news-03-list",
          title: "회원이 공지를 열어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "회원 계정으로 다시 확인했어요. 센터 이용 안내를 눌러요.",
          result: "새 공지를 열어 전체 내용을 볼 수 있어요.",
          duration: 6500,
          transition: "회원 이서준의 화면으로 바뀌었어요.",
          image: "assets/news-03-list.jpg",
          alt: "이서준(manualseojun) · 회원이 공지를 열어요. 회원 계정으로 다시 확인했어요. 센터 이용 안내를 눌러요.",
          hotspot: {
            x: 0.030232558139534883,
            y: 0.3111111111111111,
            w: 0.9395348837209302,
            h: 0.15777777777777777,
            label: "센터 이용 안내 열기",
          },
        },
        {
          id: "news-03",
          title: "센터 안내를 읽어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "수업에 늦거나 일정 변경이 필요할 때 어떻게 하면 되는지 확인해요.",
          result: "센터가 등록한 안내를 회원 화면에서 읽을 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/news-03.jpg",
          alt: "이서준(manualseojun) · 센터 안내를 읽어요. 수업에 늦거나 일정 변경이 필요할 때 어떻게 하면 되는지 확인해요.",
          hotspot: null,
        },
        {
          id: "news-04-open",
          title: "자주 묻는 질문을 준비해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "자주 묻는 질문에서 FAQ 작성을 눌러요.",
          result: "여러 번 받는 질문의 답을 모아 둘 수 있어요.",
          duration: 6500,
          transition: "다시 센터 관리자 박지은의 화면이에요.",
          image: "assets/news-04-open.jpg",
          alt: "박지은(manualmanager) · 자주 묻는 질문을 준비해요. 자주 묻는 질문에서 FAQ 작성을 눌러요.",
          hotspot: {
            x: 0.8209302325581396,
            y: 0.16,
            w: 0.11162790697674418,
            h: 0.05444444444444444,
            label: "FAQ 작성",
          },
        },
        {
          id: "news-04",
          title: "질문과 답변을 적어요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption:
            "예약과 수업 분류에 시간 변경 방법을 적었어요. 표시 순서를 정하고 FAQ 등록을 눌러요.",
          result: "작은 순서 숫자부터 질문이 보여요.",
          duration: 6500,
          transition: "",
          image: "assets/news-04.jpg",
          alt: "박지은(manualmanager) · 질문과 답변을 적어요. 예약과 수업 분류에 시간 변경 방법을 적었어요. 표시 순서를 정하고 FAQ 등록을 눌러요.",
          hotspot: {
            x: 0.07674418604651163,
            y: 0.8722222222222222,
            w: 0.8116279069767441,
            h: 0.05555555555555555,
            label: "FAQ 등록",
          },
        },
        {
          id: "news-04-confirm",
          title: "답변 등록을 확인해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "같은 센터의 회원과 운동지도자에게 보여줄 답변을 확인해요.",
          result: "확인을 누르면 질문과 답변이 등록돼요.",
          duration: 6500,
          transition: "",
          image: "assets/news-04-confirm.jpg",
          alt: "박지은(manualmanager) · 답변 등록을 확인해요. 같은 센터의 회원과 운동지도자에게 보여줄 답변을 확인해요.",
          hotspot: {
            x: 0.5116279069767442,
            y: 0.5677777777777778,
            w: 0.3953488372093023,
            h: 0.056666666666666664,
            label: "FAQ 등록 확인",
          },
        },
        {
          id: "news-05-list",
          title: "궁금한 질문을 찾아요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "회원 계정에서 자주 묻는 질문을 다시 열었어요. 궁금한 질문을 눌러요.",
          result: "검색하거나 분류를 골라 필요한 질문을 찾을 수도 있어요.",
          duration: 6500,
          transition: "회원 이서준의 화면에서 확인해요.",
          image: "assets/news-05-list.jpg",
          alt: "이서준(manualseojun) · 궁금한 질문을 찾아요. 회원 계정에서 자주 묻는 질문을 다시 열었어요. 궁금한 질문을 눌러요.",
          hotspot: {
            x: 0.030232558139534883,
            y: 0.5666666666666667,
            w: 0.9395348837209302,
            h: 0.10111111111111111,
            label: "수업 시간을 바꾸려면 어떻게 하나요? 펼치기",
          },
        },
        {
          id: "news-05",
          title: "답변을 펼쳐 읽어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "수업 시간을 바꾸는 방법이 질문 아래에 펼쳐졌어요.",
          result:
            "변경할 날짜와 시간을 선생님께 알리고, 내 일정에서 결과를 확인해요.",
          duration: 6500,
          transition: "",
          image: "assets/news-05.jpg",
          alt: "이서준(manualseojun) · 답변을 펼쳐 읽어요. 수업 시간을 바꾸는 방법이 질문 아래에 펼쳐졌어요.",
          hotspot: null,
        },
      ],
    },
    {
      id: "contact-info",
      title: "센터 연락처와 내 정보",
      summary: "센터의 연락처를 확인하고 내 연락처도 바꿔 보아요.",
      roles: ["ADMIN", "CUSTOMER"],
      category: "센터와 내 정보",
      minutes: 2,
      featured: false,
      prerequisites: [
        "센터 연락처는 센터 관리자가 등록해요.",
        "이번 안내는 연락처 등록과 조회를 보여줘요. 주소 검색의 외부 화면은 시연 범위에 포함하지 않았어요.",
      ],
      outcome:
        "회원은 센터 상세 정보에서 연락처를 확인하고, 자신의 연락처는 프로필에서 관리할 수 있어요.",
      promoStepIds: [
        "contact-01",
        "contact-02-save",
        "contact-03",
        "contact-04",
        "contact-05-confirm",
        "contact-06",
      ],
      steps: [
        {
          id: "contact-01",
          title: "센터 연락처를 입력해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "센터 설정에서 회원에게 안내할 연락처를 입력해요.",
          result: "시연용 센터 연락처를 02-0000-0000으로 등록해 볼게요.",
          duration: 6500,
          transition: "",
          image: "assets/contact-01.jpg",
          alt: "박지은(manualmanager) · 센터 연락처를 입력해요. 센터 설정에서 회원에게 안내할 연락처를 입력해요.",
          hotspot: null,
        },
        {
          id: "contact-02-save",
          title: "센터 정보를 저장해요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption: "입력한 내용을 확인하고 센터 설정 저장을 눌러요.",
          result:
            "등록한 연락처를 같은 센터의 회원과 지도자가 확인할 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/contact-02-save.jpg",
          alt: "박지은(manualmanager) · 센터 정보를 저장해요. 입력한 내용을 확인하고 센터 설정 저장을 눌러요.",
          hotspot: {
            x: 0.06746987951807229,
            y: 0.7491369390103567,
            w: 0.8313253012048193,
            h: 0.05523590333716916,
            label: "센터 설정 저장",
          },
        },
        {
          id: "contact-02",
          title: "센터 연락처가 저장됐어요",
          role: "ADMIN",
          actor: "박지은(manualmanager)",
          caption:
            "센터 연락처의 저장을 마쳤어요. 이제 회원 화면에서 확인해 볼게요.",
          result: "이번 시연에서는 주소를 등록하지 않았어요.",
          duration: 6500,
          transition: "",
          image: "assets/contact-02.jpg",
          alt: "박지은(manualmanager) · 센터 연락처가 저장됐어요. 센터 연락처의 저장을 마쳤어요. 이제 회원 화면에서 확인해 볼게요.",
          hotspot: null,
        },
        {
          id: "contact-03-open",
          title: "센터 상세 정보를 열어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "회원 계정의 센터 선택에서 상세 정보를 눌러요.",
          result: "센터의 연락처와 주소를 확인하는 창이 열려요.",
          duration: 6500,
          transition: "회원 이서준의 화면으로 바뀌었어요.",
          image: "assets/contact-03-open.jpg",
          alt: "이서준(manualseojun) · 센터 상세 정보를 열어요. 회원 계정의 센터 선택에서 상세 정보를 눌러요.",
          hotspot: {
            x: 0.10602409638554217,
            y: 0.5304948216340621,
            w: 0.7518072289156627,
            h: 0.05523590333716916,
            label: "센터 상세 정보",
          },
        },
        {
          id: "contact-03",
          title: "센터 연락처를 확인해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption:
            "관리자가 등록한 02-0000-0000을 확인할 수 있어요. 등록하지 않은 주소에는 안내가 표시돼요.",
          result:
            "상세 정보는 조회 화면이에요. 이 버튼으로 센터가 바뀌거나 가입 신청되지는 않아요.",
          duration: 8500,
          transition: "",
          image: "assets/contact-03.jpg",
          alt: "이서준(manualseojun) · 센터 연락처를 확인해요. 관리자가 등록한 02-0000-0000을 확인할 수 있어요. 등록하지 않은 주소에는 안내가 표시돼요.",
          hotspot: null,
        },
        {
          id: "contact-04",
          title: "내 연락처를 수정해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "내 프로필의 연락처와 주소에서 수정을 눌러요.",
          result: "자신의 연락처를 바꿀 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/contact-04.jpg",
          alt: "이서준(manualseojun) · 내 연락처를 수정해요. 내 프로필의 연락처와 주소에서 수정을 눌러요.",
          hotspot: {
            x: 0.7349397590361446,
            y: 0.48216340621403914,
            w: 0.1493975903614458,
            h: 0.05408515535097814,
            label: "연락처와 주소 수정",
          },
        },
        {
          id: "contact-05",
          title: "바뀐 번호를 입력해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "시연용 번호 010-0000-0001로 바꾼 뒤 저장을 눌러요.",
          result: "저장하기 전에 내용을 확인해요.",
          duration: 6500,
          transition: "",
          image: "assets/contact-05.jpg",
          alt: "이서준(manualseojun) · 바뀐 번호를 입력해요. 시연용 번호 010-0000-0001로 바꾼 뒤 저장을 눌러요.",
          hotspot: {
            x: 0.5116279069767442,
            y: 0.7552951388888889,
            w: 0.4116279069767442,
            h: 0.05555555555555555,
            label: "내 연락처 저장",
          },
        },
        {
          id: "contact-05-confirm",
          title: "내 정보 저장을 확인해요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "연락처와 주소를 저장할지 확인하고 확인을 눌러요.",
          result: "입력한 연락처가 내 프로필에 반영돼요.",
          duration: 6500,
          transition: "",
          image: "assets/contact-05-confirm.jpg",
          alt: "이서준(manualseojun) · 내 정보 저장을 확인해요. 연락처와 주소를 저장할지 확인하고 확인을 눌러요.",
          hotspot: {
            x: 0.5116279069767442,
            y: 0.5515451388888889,
            w: 0.3930232558139535,
            h: 0.05555555555555555,
            label: "변경한 연락처 확인",
          },
        },
        {
          id: "contact-06",
          title: "새 연락처가 표시됐어요",
          role: "CUSTOMER",
          actor: "이서준(manualseojun)",
          caption: "프로필에서 바뀐 연락처 010-0000-0001을 확인해요.",
          result: "센터의 연락처와 나의 연락처는 각각 관리할 수 있어요.",
          duration: 6500,
          transition: "",
          image: "assets/contact-06.jpg",
          alt: "이서준(manualseojun) · 새 연락처가 표시됐어요. 프로필에서 바뀐 연락처 010-0000-0001을 확인해요.",
          hotspot: null,
        },
      ],
    },
  ],
};
